export const webServiceEndpoint: String = 'http://localhost:8080/api-citas-providencia/public/api/';
export const urlFile: String = 'http://localhost:8080/api-citas-providencia/uploads/';
export const listEndpoints: any = {
    login: 'login',
    registroPaciente: 'registro',
    validaCuenta: 'validaRegistro',
    recuperaCuenta: 'recuperaPassword',
    actualizaCuenta: 'actualizaPassword',
    cargaPerfil: 'platform/cargar_perfil_general',
    actualizaPerfil: 'platform/editar_perfil',
    cargaFamiliares: 'platform/cargar_familiares',
    cargaParentescos: 'platform/cargar_parentesco',
    registroFamiliar: 'platform/agregar_familiar',
    anulaFamiliar: 'platform/anular_familiar',
    actualizaFamiliar: 'platform/editar_familiar',
    subeFotoPerfil: 'platform/subir_foto',
    cargaPaciente: 'platform/cargar_paciente',
    cargaCitasPendientes: 'platform/cargar_citas_pendientes',
    cargaCitasRealizadas: 'platform/cargar_citas_realizadas',
    anulaCita: 'platform/anular_cita',
    cargaEspecialidades: 'platform/cargar_especialidades',
    cargaMedicosEspecialidad: 'platform/cargar_medicos_por_especialidad',
    cargaGarantes: 'platform/cargar_garante',
    cargaCalendarioMes: 'platform/cargar_fechas_programadas',
    cargaCalendarioMock: 'platform/cargar_fechas_mock',
    cargaHorario: 'platform/cargar_horario',
    registraCita: 'platform/registrar_cita',
    registraTransaccion: 'platform/registrar_transaccion',
};